### ISSUE TITLE
no test for comparator function

### ISSUE THREAD

**Issue by wraithgar** [AmpersandJS/ampersand-filtered-subcollection#11]
https://github.com/AmpersandJS/ampersand-subcollection/issues/48

**Comment by ConneXNL** [comment]
" If you pass a function, it will be passed the model and should return the value from the model that should be used to sort. If you pass a function that names two incoming arguments it will be used as a native Array.prototype.sort, where you get passed two models and return a 1, 0, -1 to specify how they compare."

I only get a single object... the second arguments is an integer?

**Comment by lukekarrys** [comment]
Fixed by #23
