### ISSUE TITLE
Documentation on comparator is wrong

### ISSUE THREAD

**Issue by bryanspears** [AmpersandJS/ampersand-filtered-subcollection#21]
"If you pass a function that names two incoming arguments it will be used as a native Array.prototype.sort, where you get passed two models and return a 1, 0, -1 to specify how they compare."

Double checked in the source and I did not see any way this could be functioning. A quick attempt to utilize this also failed.

**Comment by kamilogorek** [comment]
I verified it and I guess you're right with this one.

According to https://github.com/AmpersandJS/ampersand-filtered-subcollection/blob/master/ampersand-filtered-subcollection.js we're using `sortBy` and `sortedIndex` lodash functions, passing `comparator` around.

But then, looking at lodash's source https://github.com/lodash/lodash/blob/3.10.0/lodash.src.js#L5491 and https://github.com/lodash/lodash/blob/3.10.0/lodash.src.js#L7258 it doesn't give us 2 values to work with (`sortBy` does, but it's `value` and `key` from `map` call).

This mention should be either removed from here + other collection-based repos, or behaviour should be aligned.
