### ISSUE TITLE
Comparator property change event is not bubbled

### ISSUE THREAD

**Issue by herkyl** [AmpersandJS/ampersand-filtered-subcollection#22]
Listening to a change event of the property that is also a comparator does not work. Example code in CoffeeScript:
```coffeescript
active = new FilteredSubcollection collection,
  where: active: true
  comparator: 'position'
this.listenTo active, 'change:position', -> console.log 'change:position' # <- is never called
```

I'm not sure if this is intended or not. If this is a bug I'd be happy to supply a pull request.

**Comment by wraithgar** [comment]
Definitely not intended.
