### ISSUE TITLE
switch to lodash 3.x modules

### ISSUE THREAD

**Issue by wraithgar** [AmpersandJS/ampersand-filtered-subcollection#6]

**Comment by klaemo** [comment]
I have a PR ready for this once `ampersand-collection-lodash-mixin` is published.

**Comment by wraithgar** [comment]
I'm thinking about burning a major version and removing the underscore mixin functionality being baked-in.  If your PR is ready just remove the underscore-mixin from this module and we can hash it out. https://github.com/AmpersandJS/ampersand-filtered-subcollection/issues/8

**Comment by klaemo** [comment]
:+1: 
The tests use the underscore mixin in a couple of places as well, should I remove it there, too? or replace it with the lodash one and move it to devDep?

**Comment by wraithgar** [comment]
remove altogether please

**Comment by klaemo** [comment]
It's actually used in quite some places. I don't have the time to finish it now. Will do it later :)

**Comment by wraithgar** [comment]
switched in `v2.0.0`
